import { ModuleContent } from '../types'

export const module9: ModuleContent = {
  id: 'module-9',
  title: 'Erreurs Courantes à Éviter',
  description: 'Identifiez et évitez les 14 erreurs les plus fréquentes en Google Ads pour protéger votre budget et maximiser vos performances',
  content: [
    '### Erreurs de stratégie : les plus coûteuses\n\nLes erreurs stratégiques sont les plus dangereuses car elles affectent l\'ensemble de vos campagnes et peuvent engloutir votre budget sans aucun retour. La première erreur majeure est de choisir un objectif de campagne inadapté. Utiliser "Trafic" quand votre véritable objectif est de générer des ventes pousse l\'algorithme à optimiser pour le mauvais KPI. Inversement, choisir "Conversions" sans avoir suffisamment de données historiques empêche l\'algorithme d\'apprendre efficacement.',
    'La solution est d\'adapter votre objectif à votre phase de maturité. En phase découverte, utilisez "Trafic" pour collecter des données. Une fois que vous atteignez 30+ conversions par mois, passez en "Conversions". Pour le scaling e-commerce avec un tracking fiable, évoluez vers "Valeur de conversion" pour maximiser le chiffre d\'affaires plutôt que le nombre de ventes.',
    'La deuxième erreur stratégique est le budget insuffisant pour l\'apprentissage. Google a besoin d\'un minimum de données pour optimiser vos campagnes. Un budget trop faible maintient vos campagnes bloquées en "Phase d\'apprentissage" indéfiniment, avec des performances très instables. Les signaux d\'alerte sont clairs : très peu d\'impressions malgré des enchères correctes, et des résultats qui fluctuent drastiquement jour après jour.',
    '**Budgets minimums recommandés par phase :**\n\n- Test de campagne : 20€/jour minimum pour collecter des données\n- Campagne optimisée : 50€/jour minimum pour des résultats stables\n- Scaling sérieux : 100€/jour et plus pour une croissance significative',
    '### Erreurs de structure de compte\n\nLa troisième erreur est d\'avoir trop de mots-clés par groupe d\'annonces. Des groupes avec 50+ mots-clés disparates rendent impossible la création d\'annonces pertinentes. Si votre groupe "Vêtements" contient à la fois "robe de soirée", "jean homme", "chaussures sport" et "veste cuir", comment écrire une annonce qui répond à toutes ces intentions ? Le test simple : pouvez-vous rédiger une seule annonce pertinente pour tous ces mots-clés ? Si non, divisez le groupe.',
    'La règle est stricte : maximum 15 mots-clés par groupe d\'annonces, avec une cohérence sémantique forte. Tous les mots-clés doivent partager la même intention de recherche. Un groupe "Chaussures Running Homme" peut contenir "chaussures running homme", "baskets course homme", "sneakers running homme", mais pas "chaussures randonnée" ni "chaussures femme".',
    '### Erreurs de ciblage : le budget qui s\'évapore\n\nLa quatrième erreur, et l\'une des plus coûteuses, est de négliger les mots-clés négatifs. Sans exclusions, vous payez pour des clics qui ne convertiront jamais. Un vendeur de chaussures neuves qui n\'exclut pas "occasion", "seconde main", "réparation" ou "pas cher" gaspille potentiellement 30-40% de son budget sur du trafic non qualifié. L\'analyse hebdomadaire du rapport des termes de recherche est obligatoire pour identifier et exclure les requêtes non pertinentes.',
    'Le ciblage géographique imprécis est la cinquième erreur fréquente. Un commerce local parisien qui cible "France entière" paie pour des clics depuis Marseille sans possibilité de conversion. Pire encore, la configuration par défaut "Personnes dans ma zone cible OU intéressées par ma zone" inclut des recherches de type "voyage Paris" qui ne correspondent pas à votre clientèle locale. Sélectionnez toujours "Personnes dans ma zone cible" pour les activités locales.',
    'Ignorer les ajustements d\'enchères est la sixième erreur. Des enchères identiques à 3h du matin et à 19h30 pour un restaurant gaspillent du budget sur des créneaux non convertisseurs. Analysez vos performances par appareil, heure et localisation, puis ajustez progressivement (±10% pour commencer) en observant les résultats.',
    '### Erreurs de création d\'annonces\n\nLa septième erreur est de créer des titres génériques qui ne vous différencient pas. "Vente de voitures" et "Meilleurs prix" ne disent rien de spécifique. Comparez avec "Citroën C3 2023 - 15,990€" et "Garantie 5 ans - Financement 0%" : la spécificité attire l\'œil et pré-qualifie le prospect. Incluez des marques, modèles, prix exacts et bénéfices concrets que vos concurrents n\'ont pas.',
    'Négliger les extensions d\'annonce est la huitième erreur. Sans extensions, votre annonce est plus petite visuellement et moins performante. Les extensions sont gratuites, augmentent le CTR de 10 à 30%, et améliorent le Quality Score. Ne pas les utiliser revient à laisser de l\'argent sur la table.',
    '**Extensions essentielles à configurer :**\n\n- Liens annexes : 4-6 liens vers vos pages importantes\n- Accroches : 4-6 arguments de vente courts\n- Lieu : Adresse si commerce physique\n- Appel : Numéro téléphone si service',
    'La neuvième erreur est de n\'avoir qu\'une seule annonce par groupe. Sans tests A/B, vous ratez des opportunités d\'optimisation significatives. Créez toujours 2-3 annonces par groupe avec des variations contrôlées (un élément différent à la fois), et renouvelez vos créations toutes les 2-4 semaines pour éviter la fatigue publicitaire.',
    '### Erreurs de mesure : voler à l\'aveugle\n\nLa dixième erreur est une mauvaise configuration du suivi des conversions. Le double comptage (pixel Google + Analytics comptant la même conversion), les conversions fantômes (pages de remerciement accessibles directement via URL), ou une fenêtre d\'attribution inadaptée faussent complètement vos données. Testez manuellement votre tracking en effectuant vous-même une conversion et vérifiez le comptage. L\'écart entre Google Ads et GA4 ne devrait pas dépasser 15%.',
    'Se focaliser sur les mauvaises métriques est la onzième erreur. Les impressions sont faciles à gonfler et ne garantissent rien. Un CTR élevé peut masquer un taux de conversion désastreux. Un CPC faible est inutile si le trafic ne convertit pas. Concentrez-vous sur les métriques qui comptent vraiment : ROAS/ROI pour la rentabilité, CPA pour le coût d\'acquisition, et part d\'impressions pour votre position sur le marché.',
    'La douzième erreur est d\'optimiser trop rapidement. Modifier vos campagnes quotidiennement empêche l\'algorithme d\'apprendre. Les nouvelles campagnes nécessitent 7-14 jours, les nouveaux mots-clés 3-7 jours, les changements d\'enchères 3-5 jours. La règle d\'or : attendez minimum 1 semaine et 50+ clics avant d\'optimiser significativement.',
    '### Erreurs budgétaires : mauvaise allocation des ressources\n\nLa treizième erreur est une répartition budgétaire uniforme entre campagnes aux performances inégales. Donner 100€/jour à chaque campagne sans considérer leur ROAS respectif est sous-optimal. Si votre campagne marque génère un ROAS de 8x et votre campagne générique un ROAS de 2x, allouez 70% de votre budget à la campagne performante. La répartition intelligente multiplie les résultats globaux.',
    'La quatorzième erreur est l\'absence de budget de test. Investir 100% du budget sur les campagnes existantes vous prive de découvrir de nouvelles opportunités. La répartition recommandée est 80% sur les campagnes et mots-clés performants établis, 15% sur l\'optimisation et le scaling des performants, et 5% sur les tests de nouveaux mots-clés, audiences et créations.',
    '### Comment éviter ces erreurs : checklist et routines\n\nAvant d\'activer une campagne, vérifiez systématiquement : objectif cohérent avec le but business, budget suffisant (minimum 20€/jour), mots-clés groupés logiquement (max 15 par groupe), annonces multiples (2-3 par groupe), extensions configurées, négatifs préventifs ajoutés, suivi des conversions testé et fonctionnel, et landing pages optimisées.',
    '**Routine de contrôle hebdomadaire :**\n\n- Lundi : Analyse performance du week-end, identification des anomalies\n- Mercredi : Rapport termes de recherche, ajout de mots-clés négatifs\n- Vendredi : Ajustements enchères, lancement de nouveaux tests A/B',
    'La formation continue est essentielle dans un écosystème qui évolue constamment. Google Skillshop propose des formations officielles gratuites, la documentation Google Ads Help répond aux questions techniques, et les communautés spécialisées partagent les retours d\'expérience du terrain. Restez curieux, testez régulièrement de nouvelles approches, et apprenez de vos erreurs autant que de vos succès.'
  ],
  keyPoints: [
    'Objectif campagne = phase de maturité : Trafic → Conversions (30+/mois) → Valeur',
    'Maximum 15 mots-clés par groupe, cohérence sémantique obligatoire',
    'Analyse hebdomadaire des termes de recherche pour les mots-clés négatifs',
    'Extensions obligatoires : +10-30% CTR, gratuites, facteur Quality Score',
    'Règle d\'or : 1 semaine + 50 clics minimum avant toute optimisation majeure'
  ]
}
