import { ModuleContent } from '../types'

export const module7: ModuleContent = {
  id: 'module-7',
  title: 'YouTube Ads : La Puissance de la Vidéo',
  description: 'Maîtrisez YouTube Ads pour exploiter la puissance de la vidéo : formats TrueView, Bumper Ads, Shorts, ciblage avancé et optimisation créative.',
  content: [
    '### L\'Écosystème YouTube en 2025\n\nYouTube représente une opportunité publicitaire exceptionnelle avec 47 millions d\'utilisateurs actifs mensuels en France, soit 70% de la population. Les utilisateurs passent en moyenne 2h15 par jour sur la plateforme, avec 60% du temps de visionnage sur mobile.',
    '**Comportement utilisateur clé :**\n\n- **500 heures** de vidéo uploadées chaque minute dans le monde\n- **1 milliard d\'heures** regardées quotidiennement\n- **76%** des utilisateurs français découvrent de nouveaux produits via YouTube\n- **85%** regardent des tutoriels avant un achat',
    '### YouTube vs TV Traditionnelle\n\nYouTube offre des avantages décisifs : ciblage précis par centres d\'intérêt, âge et comportement, mesure exacte des vues et conversions, interactivité avec call-to-action cliquables, coût maîtrisé (paiement après 30 secondes), et formats flexibles de 6 secondes à plusieurs minutes.',
    '**Position dans l\'écosystème Google Ads :**\n\n- **Intégration cross-canal** : Combiner Search, Display et Vidéo\n- **Audiences partagées** : Utiliser les mêmes listes entre campagnes\n- **Attribution unifiée** : Vision globale du parcours client\n- **Optimisation croisée** : Budget réparti automatiquement',
    '### Campagnes TrueView In-Stream\n\nLes publicités TrueView In-Stream se diffusent avant, pendant ou après les vidéos YouTube avec un bouton "Ignorer" après 5 secondes. Vous ne payez que si l\'utilisateur regarde plus de 30 secondes ou interagit avec l\'annonce.',
    '**Avantages TrueView In-Stream :**\n\n- **Audience captive** : Utilisateur déjà en mode vidéo\n- **Qualité d\'engagement** : Vues longues = intérêt réel\n- **Coût maîtrisé** : Pas de paiement si skip immédiat\n- **Durée optimale** : 15-30 secondes, accroche forte dans les 5 premières secondes',
    '### Campagnes TrueView Discovery\n\nLes TrueView Discovery apparaissent dans les résultats de recherche YouTube avec miniature, titre et description. Vous payez uniquement au clic sur la miniature, avec un CPC généralement inférieur au In-Stream.',
    '**Optimisation Discovery :**\n\n- **Miniature attractive** : Visuel impactant, texte lisible\n- **Titre accrocheur** : Inclure les mots-clés recherchés\n- **Description précise** : Bénéfice clair en 2 lignes\n- **Intention forte** : Utilisateur en recherche active',
    '### Bumper Ads : 6 Secondes d\'Impact\n\nFormat court de 6 secondes exactement, non-skippable, payé au CPM. Idéal pour la notoriété et la répétition du message de marque.',
    '**Création Bumper optimale :**\n\n- **Message unique** : Une seule idée par bumper\n- **Branding fort** : Logo visible dès la 1ère seconde\n- **Rythme rapide** : Chaque seconde compte\n- **Sans audio** : 50% regardent sans son\n- **Fréquence** : 3-5 expositions par utilisateur/semaine',
    '### YouTube Shorts Ads\n\nFormat émergent en pleine croissance (+300% de vues en 2024). Vidéos verticales (9:16) de 60 secondes maximum, placement dans le feed dédié YouTube Shorts.',
    '**Spécificités Shorts :**\n\n- **Mobile-first** : 95% des vues sur smartphone\n- **Son important** : Contrairement aux autres formats YouTube\n- **Trends** : S\'appuyer sur les tendances du moment\n- **Authenticité** : Style moins "publicitaire"\n- **Secteurs adaptés** : Mode/Beauté, Food, Gaming, Lifestyle',
    '### Ciblage par Audience\n\nTrois types d\'audiences principales pour cibler efficacement vos campagnes YouTube.',
    '**Audiences d\'Affinité :**\n\nGroupes basés sur les intérêts long-terme (passionnés auto, amateurs cuisine, parents). Idéal pour notoriété avec budgets importants.',
    '**Audiences d\'Intention d\'Achat :**\n\nPersonnes recherchant activement un produit/service basé sur recherches Google, vidéos consultées et sites visités. Taux de conversion 2-3x supérieur.',
    '**Audiences Personnalisées :**\n\nCustomer Match (upload emails/téléphones), visiteurs site (remarketing), utilisateurs app. Pour fidélisation, up-sell et abandons panier.',
    '### Ciblage Contextuel et Démographique\n\nAffinez votre ciblage avec des critères contextuels et démographiques précis.',
    '**Ciblage contextuel :**\n\n- **Par mots-clés** : Diffuser sur vidéos contenant ces termes\n- **Par thèmes** : Catégories larges (Auto, Sport, Tech) ou sous-catégories\n- **Par placements** : Chaînes ou vidéos spécifiques',
    '**Ciblage démographique :**\n\n- **Âge et genre** : Tranches de 5 ans (18-24, 25-34...)\n- **Situation parentale** : Parents, nouveaux parents, sans enfant\n- **Revenus estimés** : Produits premium vs accessibles',
    '### Structure d\'une Vidéo Efficace\n\n20% des spectateurs partent après 10 secondes : les 5 premières secondes sont cruciales pour capter l\'attention.',
    '**Structure recommandée :**\n\n- **5 premières secondes** : Accroche forte (question directe, fait surprenant, démonstration)\n- **5-45 secondes** : Solution, bénéfices, preuves, différenciation\n- **45-60 secondes** : Call-to-action, urgence, facilité du processus',
    '### Formats Vidéo par Objectif\n\nChoisissez le format adapté à votre objectif marketing.',
    '**Démonstration produit (30-90s) :**\n\nProblème (5s) → Solution en action (20s) → Résultat (10s) → CTA (5s)',
    '**Témoignage client (45-90s) :**\n\nSituation initiale → Découverte → Usage → Résultat → Recommandation. Utilisez de vraies personnes avec détails concrets.',
    '**Tutoriel/Éducatif (60-180s) :**\n\nPromesse → 3-5 étapes → Démonstration → Résultat → Approfondissement vers votre formation.',
    '### Bonnes Pratiques Techniques\n\nLa qualité technique impacte directement les performances de vos vidéos.',
    '**Qualité visuelle :**\n\n- Résolution minimum 1080p, idéal 4K\n- Stabilisateur ou trépied obligatoire\n- Éclairage naturel ou artificiel correct',
    '**Qualité audio :**\n\n- Micro externe (investissement prioritaire)\n- Éviter échos et bruits de fond\n- Niveau sonore cohérent',
    '**Montage :**\n\n- Changement de plan toutes les 3-5 secondes\n- Coupes franches plutôt qu\'effets\n- Sous-titres obligatoires (50% regardent sans son)',
    '### Métriques YouTube Spécifiques\n\nSuivez les bonnes métriques pour optimiser vos campagnes.',
    '**Métriques de visionnage :**\n\n- **Vues** : Comptabilisées après 30 secondes\n- **Taux de visionnage** : % de la vidéo regardé\n- **Rétention** : À quel moment les gens partent',
    '**Métriques d\'engagement (Earned Actions) :**\n\n- Vues organiques sur d\'autres vidéos\n- Nouveaux abonnés\n- Partages gratuits',
    '**Métriques de conversion :**\n\n- View-through (conversion après vue sans clic)\n- Click-through (conversion après clic)\n- Assisted conversions (YouTube aide la conversion finale)',
    '### Stratégies Cross-Canal\n\nMaximisez l\'impact en combinant YouTube avec d\'autres canaux.',
    '**YouTube + Google Search :**\n\nNotoriété YouTube → Recherches Google. Répartition suggérée : 70% Search / 30% YouTube.',
    '**YouTube + Meta Ads :**\n\nDécouverte Meta → Éducation YouTube. Audiences custom cross-plateforme et cohérence créative.',
    '**Retargeting avancé :**\n\nRetarget visiteurs YouTube sur Search/Display. Les engagés vidéo sont des audiences très qualifiées.'
  ],
  keyPoints: [
    '47M d\'utilisateurs actifs en France, 76% découvrent des produits via YouTube',
    'TrueView In-Stream : paiement après 30s, 5 premières secondes cruciales',
    'Bumper Ads : 6 secondes non-skippables pour notoriété et rappel',
    'YouTube Shorts : +300% de vues en 2024, format vertical mobile-first',
    'Audiences d\'intention d\'achat : taux de conversion 2-3x supérieur',
    'Sous-titres obligatoires : 50% regardent sans son',
    'Synergie cross-canal : 70% Search / 30% YouTube pour maximiser l\'impact'
  ]
}
