import { ModuleContent } from '../types'

export const module4: ModuleContent = {
  id: 'module-4',
  title: 'Maîtriser les Mots-Clés',
  description: 'Apprenez à sélectionner, organiser et optimiser vos mots-clés pour des campagnes Google Ads performantes',
  content: [
    '### L\'importance stratégique des mots-clés\n\nLes mots-clés sont le fondement de toute campagne Google Ads réussie. Ils déterminent quand vos annonces s\'affichent, à qui elles s\'adressent, et combien vous payez. Un mauvais choix de mots-clés peut gaspiller votre budget sur du trafic non qualifié, tandis qu\'une sélection judicieuse peut vous apporter des prospects ultra-ciblés à moindre coût. Comprendre l\'anatomie d\'une requête de recherche est la première étape vers la maîtrise des mots-clés.',
    '### Anatomie d\'une requête de recherche\n\nChaque requête se compose d\'un terme principal (le concept central comme "voiture" ou "plombier") et de modificateurs qui précisent l\'intention (comme "occasion", "pas cher", "Paris", "urgence"). La longueur de la requête influence directement la concurrence et le taux de conversion. Les mots-clés courts (1-2 mots) comme "voiture" ou "assurance" génèrent un volume élevé mais sont très génériques, avec une intention vague et un taux de conversion faible. Ils sont utiles principalement pour des campagnes de notoriété avec des budgets importants.',
    'Les mots-clés moyens (3-4 mots) comme "voiture occasion Paris" ou "assurance auto jeune" offrent le meilleur équilibre entre volume et qualification. Ils devraient représenter environ 70% de votre budget car ils combinent un volume de recherche correct avec une intention claire. Les mots-clés longs (5+ mots) comme "acheter voiture occasion BMW Paris 15ème" ou "assurance auto jeune conducteur moins 25 ans" ont un volume faible mais une intention très précise. Ils génèrent les meilleurs taux de conversion à moindre coût.',
    '### Les types de correspondance expliqués\n\nGoogle propose trois types de correspondance qui contrôlent la précision du déclenchement de vos annonces. La correspondance exacte [mot-clé] est la plus restrictive : votre annonce ne s\'affiche que pour le mot-clé exact ou des variantes très proches (pluriel, fautes de frappe). Par exemple, [chaussures running femme] se déclenche pour "chaussures running femme" ou "chaussure running femmes" mais pas pour "chaussures de running pour femme". Ce type offre un contrôle total et un trafic ultra-qualifié, mais limite le volume.',
    'La correspondance expression "mot-clé" est intermédiaire : votre annonce s\'affiche quand la requête contient le mot-clé exact, dans l\'ordre, mais peut avoir d\'autres mots avant ou après. Par exemple, "chaussures running femme" se déclenche pour "acheter chaussures running femme" ou "chaussures running femme Nike". C\'est généralement le type recommandé pour équilibrer contrôle et volume, représentant 60-70% des mots-clés d\'un compte bien optimisé.',
    'La correspondance large mot-clé est la plus permissive : Google déclenche vos annonces pour des recherches qu\'il juge liées à votre mot-clé, incluant synonymes et termes connexes. Par exemple, +chaussures +running +femme peut se déclencher pour "baskets jogging dame" ou "sneakers course à pied". Ce type maximise le volume mais peut générer du trafic non qualifié. Utilisez-le principalement en phase de découverte ou avec une liste de mots-clés négatifs bien fournie.',
    '### Recherche et sélection de mots-clés\n\nLa recherche de mots-clés commence par le Google Keyword Planner, accessible gratuitement dans votre compte Google Ads. Cet outil vous donne le volume de recherche mensuel, le niveau de concurrence (faible/moyen/élevé), et une fourchette d\'enchères pour apparaître en première page. Complétez avec Google Trends pour identifier les tendances saisonnières et les variations géographiques. Les outils payants comme SEMrush ou Ahrefs permettent d\'espionner les mots-clés de vos concurrents.',
    'Une approche efficace est de commencer par un brainstorming interne avec vos équipes commerciales et support client : comment vos clients décrivent-ils vos produits ? Quels problèmes cherchent-ils à résoudre ? Analysez ensuite votre site web, vos contenus existants, et les requêtes organiques dans Google Search Console. Enfin, étudiez vos concurrents : quels titres utilisent-ils dans leurs annonces ? Quels mots-clés semblent-ils cibler ?',
    '### Organisation en groupes d\'annonces\n\nLa structure de vos groupes d\'annonces est cruciale pour la performance. Le principe fondamental est la cohérence sémantique : un groupe d\'annonces doit regrouper des mots-clés suffisamment proches pour qu\'une même annonce soit pertinente pour tous. La règle pratique est de se poser la question : "Puis-je écrire une annonce qui répond à tous ces mots-clés ?" Si la réponse est non, divisez le groupe.',
    '**Structure recommandée par groupe d\'annonces :**\n\n- Maximum 15 mots-clés par groupe\n- Mots-clés sémantiquement proches avec même intention\n- 3-4 annonces pour tester différents messages\n- Exemple : "Chaussures Running Femme" avec [chaussures running femme], "chaussures running femme", baskets running femme',
    '### Les mots-clés négatifs : protégez votre budget\n\nLes mots-clés négatifs empêchent vos annonces de s\'afficher pour certaines requêtes non pertinentes. Sans cette protection, vous payez pour des clics qui ne convertiront jamais. Par exemple, si vous vendez des chaussures neuves, ajoutez "occasion", "d\'occasion", "seconde main" en négatifs. Si vous êtes positionné premium, excluez "pas cher", "discount", "gratuit". Analysez le rapport de termes de recherche chaque semaine pour identifier les requêtes non pertinentes qui génèrent des clics.',
    'Les mots-clés négatifs peuvent être appliqués à trois niveaux. Au niveau du groupe d\'annonces pour des exclusions très spécifiques (exclure "homme" dans le groupe "Chaussures Running Femme"). Au niveau de la campagne pour des exclusions qui s\'appliquent à tous les groupes (exclure "gratuit", "emploi", "formation"). Au niveau du compte via des listes partagées pour des termes génériques jamais pertinents pour votre activité.',
    '### Optimisation continue des mots-clés\n\nL\'optimisation des mots-clés est un processus continu, pas une tâche ponctuelle. Le Quality Score est votre indicateur principal : une note de 7+ est l\'objectif pour chaque mot-clé. Si la pertinence de l\'annonce est faible, incluez le mot-clé dans le titre. Si l\'expérience de la page est faible, améliorez la vitesse de chargement et ajoutez le mot-clé dans le contenu. Si le CTR attendu est faible, testez des annonces plus attractives avec des call-to-action plus incitatifs.',
    'Analysez régulièrement les performances de vos mots-clés. Les mots-clés performants (bon taux de conversion, CPA acceptable) méritent des enchères plus élevées pour capturer plus de trafic. Les mots-clés coûteux sans conversion doivent être baissés ou mis en pause. Les nouveaux mots-clés doivent démarrer avec des enchères modérées et être ajustés après avoir collecté suffisamment de données (minimum 100 clics ou 2 semaines).'
  ],
  keyPoints: [
    'Mots-clés moyens (3-4 mots) = 70% du budget, meilleur équilibre volume/qualification',
    'Correspondance expression "mot-clé" recommandée pour 60-70% des mots-clés',
    'Maximum 15 mots-clés par groupe d\'annonces, cohérence sémantique obligatoire',
    'Analyser le rapport de termes de recherche chaque semaine pour les négatifs',
    'Quality Score 7+ = objectif pour chaque mot-clé, CPC divisé par 2 avec QS 8 vs 4'
  ]
}
