import { ModuleContent } from '../types'

export const module5: ModuleContent = {
  id: 'module-5',
  title: 'Créer des Annonces Efficaces',
  description: 'Maîtrisez l\'art de rédiger des annonces Google Ads qui convertissent grâce aux techniques de copywriting et aux extensions',
  content: [
    '### Anatomie d\'une annonce Google Ads\n\nUne annonce Google Ads se compose de plusieurs éléments obligatoires et optionnels qui, ensemble, déterminent son efficacité. Comprendre chaque composant est essentiel pour créer des annonces qui captent l\'attention et génèrent des clics qualifiés. Les titres sont la première chose que l\'utilisateur voit : vous disposez de 3 titres de 30 caractères maximum chacun. Google peut afficher 1, 2 ou 3 titres selon l\'espace disponible, c\'est pourquoi votre titre 1 doit toujours être le plus percutant et contenir votre mot-clé principal.',
    'Les descriptions permettent de développer votre argument de vente. Vous avez 2 descriptions de 90 caractères maximum chacune, généralement toutes deux affichées. C\'est l\'espace pour détailler vos bénéfices, vos garanties et votre call-to-action. L\'URL finale est la page sur laquelle atterrit l\'utilisateur après avoir cliqué. Elle doit absolument correspondre au contenu promis dans l\'annonce pour maintenir un bon Quality Score et éviter les rebonds.',
    'Les chemins d\'affichage sont optionnels mais recommandés. Ce sont les 2 segments de 15 caractères qui s\'affichent après votre domaine (exemple : nike.com/chaussures/running). Ils donnent à l\'utilisateur une idée du contenu de la page et améliorent la confiance. Contrairement à l\'URL finale, ils n\'ont pas besoin de correspondre à une vraie URL de votre site.',
    '### L\'importance de la correspondance annonce/mot-clé\n\nLa règle d\'or en Google Ads est que votre mot-clé principal doit apparaître au moins une fois dans votre annonce, idéalement dans le titre 1. Cette correspondance est un facteur majeur du Quality Score et influence directement votre coût par clic. Quand un utilisateur recherche "plombier Paris 15" et voit une annonce avec ce terme exact en titre, la pertinence est maximale et le CTR grimpe naturellement.',
    'Le Dynamic Keyword Insertion (DKI) est une fonctionnalité puissante qui insère automatiquement le mot-clé recherché dans votre annonce. La syntaxe est {KeyWord:Texte par défaut}. Par exemple, un titre "{KeyWord:Plombier} Paris - Intervention Rapide" affichera "Plombier D\'urgence Paris - Intervention Rapide" si l\'utilisateur a cherché "plombier d\'urgence". Cette personnalisation dynamique améliore considérablement le CTR et le Quality Score, mais attention : vérifiez que tous les mots-clés de votre groupe fonctionnent grammaticalement avec le DKI.',
    '### Techniques de persuasion en copywriting\n\nUne erreur classique est de confondre caractéristiques et bénéfices. "Formation 40 heures" est une caractéristique. "Maîtrisez Excel en 40h" est un bénéfice. Le bénéfice répond à la question "Qu\'est-ce que ça m\'apporte ?". Vos annonces doivent toujours mettre en avant ce que le client gagne, pas ce que vous faites. Transformez "Garage 15 ans d\'expérience" en "Réparation garantie par 15 ans d\'expertise" pour créer une connexion émotionnelle.',
    'L\'urgence et la rareté sont des leviers psychologiques puissants. L\'urgence temporelle ("Offre limitée jusqu\'au 31/12", "24h pour profiter de -30%") crée un sentiment de FOMO. La rareté quantitative ("Plus que 3 places disponibles", "Stock limité") déclenche l\'action immédiate. La rareté géographique ("Seul distributeur agréé Paris") établit votre unicité. Utilisez ces techniques avec parcimonie et honnêteté pour maintenir la confiance.',
    '**Preuves sociales efficaces :**\n\n- Chiffres clients : "Déjà 1500+ clients satisfaits", "Note moyenne 4,8/5"\n- Certifications : "Certifié ISO 9001", "Label RGE Qualibat"\n- Médias : "Vu dans Le Figaro", "Élu meilleur service 2024"',
    '### L\'art du call-to-action\n\nUn call-to-action (CTA) faible comme "Cliquez ici" ou "En savoir plus" ne donne aucune raison de cliquer. Un CTA fort décrit l\'action concrète et son bénéfice immédiat. "Obtenez votre devis gratuit" promet un résultat tangible. "Réservez votre place maintenant" crée l\'urgence. "Commandez avant 16h = livré demain" combine action et récompense. Le meilleur CTA répond à la question : "Qu\'est-ce que je vais obtenir exactement en cliquant ?"',
    '### Optimisation pour le mobile\n\nAvec plus de 60% des recherches effectuées sur mobile, l\'optimisation mobile n\'est plus optionnelle. L\'écran réduit signifie moins d\'espace : vos titres risquent d\'être tronqués après 20-25 caractères. Placez donc l\'information essentielle en début de titre. L\'utilisateur mobile est souvent pressé et en situation de mobilité, privilégiez les messages courts et percutants qui vont droit au but.',
    '**Bonnes pratiques mobiles :**\n\n- Messages courts : Phrases concises, mots simples, aller à l\'essentiel\n- CTA adaptés : "Appelez maintenant" (clic to call), "Itinéraire" (commerces locaux)\n- Extensions mobiles : Extension d\'appel obligatoire, extension de lieu pour le local',
    '### Tests A/B : la clé de l\'optimisation continue\n\nNe jamais deviner ce qui fonctionne : testez. Créez 2-3 annonces par groupe d\'annonces avec une seule variable différente à la fois. Si vous changez le titre ET la description, vous ne saurez pas ce qui a fait la différence. Testez d\'abord le titre 1 seul, puis la description, puis l\'angle d\'approche (bénéfice vs prix vs urgence). Configurez la rotation sur "Equal rotation" au début, puis passez en "Optimize for clicks" après avoir collecté des données.',
    'La significativité statistique est cruciale. Attendez minimum 2 semaines ou 100 clics par annonce avant de tirer des conclusions. Un écart de performance inférieur à 10% n\'est pas significatif. Entre 10-20%, vous avez une tendance à confirmer. Au-delà de 20%, vous avez un gagnant clair. Gardez l\'annonce performante et créez une nouvelle variation pour continuer à optimiser.',
    '### Les extensions d\'annonce : votre avantage concurrentiel\n\nLes extensions d\'annonce sont gratuites mais augmentent la taille visuelle de votre annonce et améliorent le CTR de 10 à 30%. Elles sont également un facteur positif du Quality Score. Ne pas les utiliser, c\'est laisser de l\'argent sur la table. Les extensions de liens annexes (sitelinks) ajoutent 4 à 6 liens vers d\'autres pages de votre site : "Nouveautés", "Promotions", "Livraison", "Contact". Chaque lien a un titre de 25 caractères et une description optionnelle de 35 caractères.',
    'Les extensions d\'accroche (callouts) sont des textes courts sans lien qui mettent en avant vos arguments de vente : "Livraison gratuite", "Retour 30 jours", "20 ans d\'expérience", "Devis gratuit". Les extensions structurées (structured snippets) listent des catégories spécifiques comme vos marques, services ou destinations. Par exemple, un garage peut lister "Services : Révision, Réparation, Contrôle technique, Carrosserie".',
    '**Extensions essentielles par type d\'activité :**\n\n- E-commerce : Liens (Nouveautés, Promos, Livraison), Accroches (Retour gratuit, Paiement sécurisé), Prix\n- Services : Liens (Tarifs, Devis, Contact), Accroches (Intervention 24h, Certifié), Appel, Lieu\n- B2B : Liens (Nos clients, Cas d\'études, Démo), Accroches (Support technique, Formation incluse)',
    '### Extensions de lieu et d\'appel : indispensables pour le local\n\nL\'extension de lieu nécessite une fiche Google My Business validée et affiche votre adresse complète, numéro de téléphone, horaires, bouton d\'itinéraire et note moyenne. Pour les commerces physiques et services à domicile, c\'est un must absolu. L\'extension d\'appel permet aux utilisateurs mobiles d\'appeler directement sans visiter votre site. Activez le suivi des appels via un numéro Google pour mesurer précisément les conversions téléphoniques.',
    '### Extension de prix : transparence qui convertit\n\nL\'extension de prix affiche une grille tarifaire directement dans votre annonce. Elle est particulièrement efficace pour les services standardisés avec des tarifs clairs. Un plombier peut afficher "Dépannage urgence : À partir de 80€", "Réparation fuite : À partir de 120€". Cette transparence pré-qualifie les prospects : ceux qui cliquent acceptent déjà votre gamme de prix, augmentant significativement le taux de conversion.',
    '### Cycle d\'optimisation continue\n\nL\'optimisation des annonces n\'est jamais terminée. En semaines 1-2, observez sans modifier : collectez les données et identifiez les tendances. En semaines 3-4, pausez les annonces clairement sous-performantes et dupliquez les meilleures avec des variations. À partir du mois 2, renouvelez vos créations toutes les 2-4 semaines, adaptez aux périodes saisonnières (soldes, fêtes), et surveillez ce que font vos concurrents pour vous inspirer des nouvelles approches du marché.'
  ],
  keyPoints: [
    'Mot-clé principal obligatoire dans le titre 1 pour maximiser le Quality Score',
    'Bénéfices > Caractéristiques : répondez à "Qu\'est-ce que ça m\'apporte ?"',
    'Extensions gratuites = +10-30% CTR, à utiliser systématiquement',
    'Tests A/B : une seule variable, minimum 100 clics, écart >20% = gagnant clair',
    'Mobile first : titres courts, CTA adaptés, extensions d\'appel obligatoires'
  ]
}
