import { ModuleContent } from '../types'

export const module10: ModuleContent = {
  id: 'module-10',
  title: 'Cas Pratiques par Secteur',
  description: 'Découvrez trois études de cas détaillées : cabinet d\'avocats, e-commerce mode, et plombier local avec stratégies, résultats et apprentissages',
  content: [
    '### Cas pratique 1 : Cabinet d\'avocats spécialisé divorce\n\nCe cabinet parisien spécialisé en droit de la famille et divorce cherchait à générer 10-15 nouveaux dossiers par mois avec un budget de 2000€. La zone d\'intervention couvre Paris et la petite couronne (20km). L\'analyse préliminaire a révélé une forte saisonnalité : pics en janvier (résolutions de nouvelle année) et septembre (rentrée, nouvelles décisions), creux en décembre pendant les fêtes.',
    'L\'étude des mots-clés a identifié plusieurs opportunités : "avocat divorce Paris" génère 800 recherches mensuelles avec un CPC de 3,50€, "procédure divorce" atteint 1200 recherches à 2,80€, "garde enfants divorce" représente 400 recherches à 4,20€. La concurrence est forte sur les mots-clés géographiques mais modérée sur les termes informationnels, avec des CPC moyens secteur entre 2,50€ et 5€.',
    'La structure de campagnes mise en place comprend trois volets. La campagne principale "Avocat Divorce Local" avec 1000€/mois cible les requêtes géographiques directes comme "avocat divorce paris", "avocat divorce vincennes" et "cabinet avocat famille paris". La campagne "Procédures Divorce" avec 700€/mois capture les recherches informationnelles : "procédure divorce", "comment divorcer", "divorce amiable", "divorce contentieux". La campagne "Garde et Pension" avec 300€/mois cible des requêtes plus spécifiques à forte valeur.',
    '**Exemple d\'annonce performante :**\n\n- Titre 1 : "Avocat Divorce Paris - Maître Durand"\n- Titre 2 : "20 ans d\'expérience - 1er RDV Gratuit"\n- Description : "Avocat spécialisé divorce amiable et contentieux. Accompagnement personnalisé, honoraires transparents."',
    'Les extensions d\'annonce incluent des liens annexes vers "/tarifs-avocat-divorce", "/rdv-gratuit", "/droit-famille" et "/contact", des accroches comme "20 ans d\'expérience", "1er rendez-vous gratuit", "Honoraires transparents", plus les extensions de lieu et d\'appel avec suivi activé.',
    'Après 6 mois, les résultats sont impressionnants. Le budget mensuel moyen de 1950€ génère 45000 impressions, 380 clics (CTR 2,4%, excellent pour le secteur), avec un CPC moyen de 3,20€. Les conversions se répartissent entre 28 appels téléphoniques qualifiés (>60 secondes) et 12 formulaires de contact par mois, soit 40 leads mensuels avec un taux de conversion de 10,5% et un CPA de 48€.',
    'Le résultat business final : 14 nouveaux dossiers signés par mois en moyenne, soit un taux de transformation lead-client de 35%. Avec un CA moyen de 2800€ par dossier, le ROAS atteint 20:1 (39200€ de CA pour 1950€ de publicité). Les optimisations successives ont inclus l\'ajout de mots-clés négatifs ("gratuit", "aide juridictionnelle", "pro bono"), des ajustements horaires (-30% entre 12h-14h et après 19h), et des landing pages spécialisées par type de divorce.',
    '**Apprentissages clés du secteur juridique :**\n\n- Les appels convertissent mieux que les formulaires (45% vs 25% de transformation)\n- L\'angle "expérience" surpasse l\'angle "prix" (+30% CTR)\n- La saisonnalité est très marquée : adapter les budgets selon les périodes',
    '### Cas pratique 2 : E-commerce mode masculine\n\nCette boutique en ligne de vêtements homme (25-50 ans) dispose d\'un catalogue de 2500 produits (costumes, casual, accessoires), génère 1,2M€ de CA annuel avec un panier moyen de 85€ et une marge de 45%. L\'objectif était d\'augmenter le CA de 40% via Google Ads. Les forces identifiées incluent un catalogue large, des photos professionnelles, un site mobile-friendly avec checkout fluide, et des avis clients excellents (4,6/5 sur 850+ avis).',
    'La stratégie multi-campagnes déployée repose sur trois piliers. Les campagnes Shopping (2500€/mois) sont le cœur du dispositif avec un flux produit de 2500 références actualisées quotidiennement, des titres optimisés (Marque + Type + Couleur + Taille), des images fond blanc haute résolution, et un benchmarking prix automatique. La structure comprend Shopping Standard (enchères manuelles), Shopping Smart (30% du budget, machine learning) et Shopping Marques (produits premium).',
    'Les campagnes Search (2000€/mois) se décomposent en quatre segments : campagne Marque Propre (500€) pour la protection, campagne Produits Génériques (800€) ciblant "chemise homme", "costume mariage", "jean slim homme", campagne Marques Distribuées (400€) pour "hugo boss costume" ou "ralph lauren chemise", et campagne Long Tail (300€) pour les requêtes 4+ mots à CPC bas mais très qualifiées.',
    'Les campagnes Display Remarketing (500€/mois) ciblent trois audiences : visiteurs 30 jours (créations générales marque), abandons panier (produits consultés + promo), et acheteurs existants (cross-sell, nouveautés). Les formats utilisent des bannières responsive, des bannières produits dynamiques et des vidéos lookbooks saisonniers.',
    'Après 12 mois, les performances par canal sont distinctes. Shopping génère un ROAS de 4,2x et représente 65% du CA avec un CPC moyen de 0,75€ et un taux de conversion de 3,8%. Search atteint un ROAS de 3,1x pour 25% du CA, CPC moyen 1,85€, conversion 2,2%. Display Remarketing affiche un ROAS de 2,8x pour 10% du CA avec un CPM de 3,20€.',
    '**Résultats globaux e-commerce :**\n\n- Budget mensuel : 4800€\n- CA généré : 18500€/mois\n- ROAS global : 3,85x\n- Augmentation CA total : +47% (objectif dépassé)',
    'Les optimisations spécifiques e-commerce incluent l\'intégration des promotions et soldes dans le flux Shopping, la gestion du stock en temps réel pour éviter les ruptures, les custom labels pour segmenter par marge et saisonnalité, les Dynamic Search Ads pour l\'auto-génération d\'annonces, et l\'adaptation saisonnière avec +80% de budget en Q4 et des campagnes dédiées soldes.',
    '### Cas pratique 3 : Plombier-chauffagiste local\n\nCet artisan avec une équipe de 4 personnes (artisan + 3 ouvriers) intervient sur Paris et petite couronne (50km max) pour la plomberie, chauffage et dépannage urgence. L\'objectif était de générer 20-25 interventions supplémentaires par mois. L\'analyse du marché local révèle que 75% des recherches sont mobiles (situations d\'urgence), 80% des conversions passent par appel téléphonique, et 60% des requêtes incluent "près de moi".',
    'Les recherches locales clés sont "plombier paris" (4400/mois), "plombier urgence" (1900/mois), "fuite eau" (2700/mois) et "réparation chaudière" (1200/mois). La concurrence inclut des plateformes (Hellocasa, PagesJaunes), 20+ artisans locaux sur Paris, et des réseaux nationaux (HomeServe, Engie).',
    'La stratégie hyper-locale déployée comprend trois campagnes. La campagne Urgences (800€/mois) cible un rayon de 25km en 24h/24 avec des mots-clés comme "plombier urgence paris", "fuite eau urgence", "dépannage plomberie", "plombier dimanche", "plombier nuit". La campagne Services Planifiés (500€/mois) cible 50km pendant les horaires bureau pour "installation chaudière", "rénovation salle bain", "devis plomberie". La campagne Entretien (200€/mois) est saisonnière (septembre-novembre) pour "entretien chaudière obligatoire", "ramonage paris".',
    'Le ciblage géographique avancé applique des modificateurs d\'enchères : Paris centre +50%, banlieue proche enchères normales, grande couronne -20%. Les horaires de diffusion sont adaptés : urgences 24h/24 avec +30% d\'enchères 19h-8h, services 7h-19h semaine et 9h-17h week-end, entretien 8h-18h semaine uniquement.',
    '**Créations adaptées mobile - Urgences :**\n\n- Titre 1 : "Plombier Urgence Paris - 30min"\n- Titre 2 : "Dépannage 24h/24 - Devis Gratuit"\n- Description : "Fuite, canalisation bouchée ? Intervention rapide. 20 ans d\'expérience, tarifs transparents."',
    'Après 8 mois, les performances téléphoniques montrent 95 appels qualifiés par mois d\'une durée moyenne de 3min20s, avec un taux de transformation de 65%, générant 62 interventions mensuelles. La répartition géographique révèle que Paris intra-muros représente 40% des appels avec 70% de transformation, la petite couronne 45% des appels avec 60% de transformation, et la grande couronne 15% des appels avec 45% de transformation.',
    'La saisonnalité observée montre +60% d\'urgences chauffage en hiver, +40% de rénovations au printemps, et -30% d\'activité globale en été. Le ROI final : budget mensuel 1450€, CA moyen par intervention 180€, CA mensuel généré 11160€, soit un ROAS de 7,7x.',
    'Les spécificités du marketing local qui ont fait la différence incluent une fiche Google My Business optimisée avec photos d\'interventions et avis clients, des posts réguliers avec actualités et conseils, une stratégie active de collecte d\'avis post-intervention avec réponses systématiques, et un suivi offline rigoureux avec numéros de transfert et CRM simple pour tracer l\'origine de chaque client.',
    '**Apprentissages clés du secteur services locaux :**\n\n- Mobile = 80% du trafic, optimisation cruciale\n- Extensions d\'appel essentielles : 85% des conversions par téléphone\n- Géolocalisation précise impacte drastiquement les performances\n- Urgences : CPC plus élevés mais taux de conversion supérieur\n- Avis Google My Business : +25% de conversion avec note >4,5★'
  ],
  keyPoints: [
    'Cabinet avocats : ROAS 20:1, appels > formulaires, angle expérience > prix',
    'E-commerce mode : Shopping = 65% du CA et meilleur ROAS, remarketing essentiel',
    'Plombier local : 80% mobile, 85% conversions par téléphone, ROAS 7,7x',
    'Adaptation saisonnière indispensable dans tous les secteurs',
    'Google My Business crucial pour le local : +25% conversion avec bons avis'
  ]
}
