import { ModuleContent } from '../types'

export const module2: ModuleContent = {
  id: 'module-2',
  title: 'Pourquoi Google Ads Fonctionne',
  description: 'Comprenez la psychologie de la recherche et le système d\'enchères qui fait le succès de Google Ads',
  content: [
    '### La psychologie de la recherche Google\n\nQuand un utilisateur tape une requête sur Google, il exprime bien plus qu\'une simple curiosité. Il révèle une intention, un besoin, parfois une urgence. Prenons l\'exemple de quelqu\'un qui recherche "acheter iPhone 15 Paris". Cette requête contient quatre informations cruciales : le produit souhaité (iPhone 15), l\'action envisagée (acheter), la localisation (Paris), et implicitement l\'urgence (maintenant). Cette richesse d\'intention fait de Google Ads un canal publicitaire extraordinairement qualifié.',
    '### Les quatre types d\'intentions de recherche\n\nToutes les recherches ne se valent pas d\'un point de vue publicitaire. Les recherches navigationnelles, comme "Facebook login" ou "Gmail", représentent environ 10% des requêtes et offrent peu d\'opportunités car l\'utilisateur sait déjà où il veut aller. Les recherches informationnelles, telles que "comment réparer un iPhone" ou "météo Paris", représentent 60% des requêtes. Elles sont intéressantes pour établir votre autorité mais convertissent moins directement.',
    'Les vraies opportunités publicitaires se trouvent dans les recherches transactionnelles et commerciales. Les recherches transactionnelles comme "acheter iPhone", "réserver hôtel Paris" ou "devis assurance auto" représentent 20% des requêtes et affichent les meilleurs taux de conversion car l\'utilisateur est prêt à passer à l\'action. Les recherches commerciales comme "meilleur iPhone 2025" ou "comparatif assurance auto" représentent 10% des requêtes et captent les utilisateurs en phase de considération, juste avant l\'achat.',
    '### Comment Google détermine quelles annonces afficher\n\nChaque recherche déclenche une enchère instantanée entre tous les annonceurs qui ciblent ce mot-clé. Cette enchère se déroule en moins de 200 millisecondes, le temps que la page de résultats s\'affiche. Google identifie d\'abord tous les annonceurs éligibles, puis calcule un score de classement (Ad Rank) pour chacun, et enfin affiche les annonces gagnantes dans l\'ordre de leur score.',
    '### La formule du Ad Rank expliquée\n\nLe classement de votre annonce ne dépend pas uniquement de votre enchère. Google utilise une formule qui combine trois facteurs : votre enchère maximum, votre Quality Score, et l\'impact attendu de vos extensions d\'annonce. La formule simplifiée est : Ad Rank = Enchère × Quality Score × Impact des Extensions. Cette approche signifie qu\'un annonceur avec un excellent Quality Score peut apparaître au-dessus d\'un concurrent qui enchérit plus cher.',
    '**Exemple concret de calcul Ad Rank :**\n\n- Annonceur A : Enchère 2€ × Quality Score 3 × Extensions 1.0 = Ad Rank 6\n- Annonceur B : Enchère 1€ × Quality Score 8 × Extensions 1.2 = Ad Rank 9.6\n- Résultat : B apparaît en première position malgré une enchère 2× inférieure',
    '### Le Quality Score : la clé pour réduire vos coûts\n\nLe Quality Score est une note de 1 à 10 que Google attribue à chaque mot-clé de votre compte. Cette note évalue trois composantes principales. La pertinence de votre annonce par rapport au mot-clé compte pour environ 30% du score : votre titre et description doivent correspondre à ce que l\'utilisateur recherche. L\'expérience de la page de destination représente 25% : votre site doit être rapide, mobile-friendly, et contenir le contenu promis par l\'annonce.',
    'Le facteur le plus important, représentant 45% du score, est le CTR attendu (Click-Through Rate). Google prédit la probabilité que les utilisateurs cliquent sur votre annonce en se basant sur l\'historique de votre compte et de vos annonces. Un Quality Score de 8 au lieu de 4 peut diviser votre coût par clic par deux à position égale. C\'est pourquoi l\'optimisation du Quality Score est souvent plus rentable que l\'augmentation des enchères.',
    '### L\'écosystème de recherche Google en détail\n\nGoogle Search reste le cœur du système avec 8,5 milliards de recherches mensuelles en France. Les annonces textuelles occupent les 3-4 premières positions et les 3 dernières de chaque page de résultats. La position 1 capte environ 40% des clics, les positions 2-3 captent 25%, et les positions 4 et plus se partagent les 10% restants. Les sites partenaires du réseau de recherche génèrent environ 15% du trafic total, souvent avec des CPC inférieurs mais une audience parfois moins qualifiée.',
    '### Google Maps et la recherche locale\n\nAvec 46% des recherches Google ayant une intention locale, le référencement sur Google Maps est devenu crucial pour les commerces physiques. Les annonces de lieu apparaissent sous forme d\'épingles sponsorisées sur la carte et de fiches enrichies dans les résultats locaux. Ces formats affichent votre adresse, horaires, téléphone, avis clients et même un bouton d\'itinéraire. Pour les services de proximité comme les restaurants, plombiers ou médecins, le local représente souvent la majorité du trafic qualifié.'
  ],
  keyPoints: [
    'Recherches transactionnelles (20%) = meilleurs taux de conversion, intention d\'achat claire',
    'Ad Rank = Enchère × Quality Score × Extensions, pas uniquement le budget qui compte',
    'Quality Score 8 vs 4 = CPC divisé par 2 à position égale',
    'Position 1 capte 40% des clics, positions 2-3 captent 25%',
    '46% des recherches ont une intention locale, crucial pour les commerces physiques'
  ]
}
