import { ModuleContent } from '../types'

export const module8: ModuleContent = {
  id: 'module-8',
  title: 'Mesurer et Optimiser',
  description: 'Configurez le suivi des conversions, maîtrisez les métriques essentielles et optimisez vos campagnes avec Google Analytics 4 et les rapports avancés.',
  content: [
    '### Configuration du Suivi des Conversions\n\nLe suivi des conversions est la base de toute optimisation efficace. Sans mesure précise, impossible d\'optimiser vos campagnes correctement.',
    '**Types de conversions Google Ads :**\n\n- **Site web** : Achat, lead, inscription, téléchargement, pages clés\n- **Hors ligne** : Appels téléphoniques, visites en magasin, imports CRM\n- **Application** : Installation, première ouverture, achats in-app',
    '### Fenêtres d\'Attribution\n\nLa fenêtre d\'attribution détermine combien de temps après un clic une conversion est attribuée à votre annonce.',
    '**Click-through conversions :**\n\n- **1 jour** : Attribution courte, budgets serrés\n- **7 jours** : Standard pour la plupart des secteurs\n- **30 jours** : Cycles d\'achat longs (immobilier, automobile)\n- **90 jours** : B2B, services professionnels',
    '**View-through (Display/YouTube) :**\n\n- **1 jour** : Standard, évite sur-attribution\n- **Désactivé** : Si attribution trop incertaine',
    '### Installation Technique du Suivi\n\nDeux méthodes principales pour installer le tracking Google Ads sur votre site.',
    '**Pixel de conversion (gtag.js) :**\n\nInstallation sur toutes les pages avec le Global Site Tag, puis événement de conversion spécifique sur la page de confirmation (achat, lead, etc.).',
    '**Google Tag Manager (recommandé) :**\n\n- Gestion centralisée de tous les tags\n- Modifications sans développeur\n- Mode aperçu pour tests\n- Historique et rollback possibles',
    '### Suivi des Appels Téléphoniques\n\nEssentiel pour les services et commerces locaux où le téléphone génère des conversions.',
    '**Extensions d\'appel avec suivi :**\n\n- **Numéro de transfert** : Google fournit un numéro unique\n- **Durée minimum** : Définir quelle durée = conversion (ex: 60s)\n- **Attribution précise** : Savoir quel mot-clé génère l\'appel\n- **Optimisation** : Enchères selon performance téléphonique',
    '### Import de Conversions Hors Ligne\n\nRemontez dans Google Ads les ventes conclues en magasin ou par téléphone après un clic.',
    '**Process d\'import :**\n\n1. **GCLID capture** : Paramètre Google dans l\'URL de destination\n2. **Stockage CRM** : Associer GCLID au prospect\n3. **Import fichier** : CSV avec GCLID + valeur de conversion\n4. **Attribution** : Google lie la conversion au clic initial',
    '### Métriques de Performance\n\nComprenez les métriques clés pour piloter vos campagnes efficacement.',
    '**Volume et visibilité :**\n\n- **Impressions** : Nombre d\'affichages de vos annonces\n- **Part d\'impressions** : % obtenues vs disponibles (objectif >80%)\n- **Position** : Top % et Abs Top % (objectif >70% en haut)',
    '**Engagement :**\n\n- **Clics** : Nombre de clics sur vos annonces\n- **CTR** : (Clics ÷ Impressions) × 100\n- **Benchmarks CTR** : Services 2-4%, E-commerce 1.5-3%, B2B 1-2%',
    '**Coûts :**\n\n- **CPC** : Prix moyen payé par clic\n- **CPM** : Coût pour 1000 impressions (Display/YouTube)\n- **Facteurs** : Concurrence, Quality Score, enchères',
    '### Métriques de Conversion\n\nLes métriques de conversion mesurent votre ROI réel.',
    '**Conversions :**\n\n- **Nombre** : Actions souhaitées réalisées\n- **Taux de conversion** : (Conversions ÷ Clics) × 100\n- **Benchmarks** : E-commerce 2-5%, Lead gen 5-15%, B2B 2-4%',
    '**Coût et valeur :**\n\n- **CPA** : Budget dépensé ÷ Conversions (objectif <30% marge)\n- **ROAS** : CA ÷ Coût publicitaire\n- **Benchmarks ROAS** : Minimum 2:1, bon 3-4:1, excellent 5:1+',
    '### Google Analytics 4 Integration\n\nLiez GA4 à Google Ads pour une vision complète du parcours client.',
    '**Configuration de base :**\n\n1. Associer Google Ads et GA4\n2. Importer les conversions GA4 dans Google Ads\n3. Activer les audiences GA4 pour le retargeting\n4. Configurer l\'attribution cross-device',
    '**Métriques comportementales GA4 :**\n\n- **Taux de rebond** : Qualité du trafic généré\n- **Pages par session** : Engagement sur site\n- **Durée de session** : Intérêt pour le contenu\n- **Parcours** : Entonnoirs et chemins de conversion',
    '### Rapports Google Ads Essentiels\n\nTrois rapports indispensables pour optimiser vos campagnes.',
    '**Rapport Termes de Recherche :**\n\nVoir les requêtes exactes qui déclenchent vos annonces. Ajouter les termes performants, exclure les non pertinents.',
    '**Rapport d\'Enchères :**\n\nPart d\'impressions perdue (budget ou classement), CPC vs enchère max pour identifier les marges de manœuvre.',
    '**Rapport Démographique :**\n\nPerformance par âge, sexe, revenus. Ajustez enchères et créations selon les segments performants.',
    '### Cycle d\'Optimisation Hebdomadaire\n\nStructurez votre routine d\'optimisation pour des résultats constants.',
    '**Lundi - Analyse week-end :**\n\nAjuster budgets selon saisonnalité, analyser nouveaux termes de recherche.',
    '**Mercredi - Optimisation mots-clés :**\n\nTop 20% : augmenter enchères. Bottom 20% : réduire ou pauser. Ajouter négatifs.',
    '**Vendredi - Tests et nouveautés :**\n\nNouvelles annonces, nouveaux mots-clés, ajustements ciblage.',
    '### Optimisations Mensuelles\n\nAnalyses plus profondes et tests structurés.',
    '**Tests A/B structurés :**\n\n- Semaine 1 : Test annonces (titres/descriptions)\n- Semaine 2 : Test landing pages\n- Semaine 3 : Test audiences/ciblages\n- Semaine 4 : Analyse résultats et implémentation',
    '**Veille concurrentielle :**\n\nAuction Insights, Keyword Planner, recherche manuelle des annonces concurrents.',
    '### Optimisations Saisonnières\n\nAdaptez vos campagnes aux variations saisonnières de votre marché.',
    '**Q4 E-commerce :**\n\n- Budgets +50-100% novembre-décembre\n- Mots-clés "Cadeau", "Black Friday", "Noël"\n- Extensions promotions et livraison express',
    '**Été B2B :**\n\n- Réduction budgets -30-50% juillet-août\n- Exclure périodes de congés\n- Messages préparation rentrée',
    '### Résolution des Problèmes Courants\n\nDiagnostiquez et corrigez rapidement les problèmes de performance.',
    '**Checklist diagnostic 5 minutes :**\n\n1. Budget épuisé ? Vérifier statut campagnes\n2. Concurrence nouvelle ? Analyser Auction Insights\n3. Saisonnalité ? Comparer année précédente\n4. Modifications récentes ? Historique des changements\n5. Problèmes techniques ? Vérifier site/landing pages',
    '**Conversions qui ne remontent pas :**\n\n1. Pixel installé ? Tester avec Google Tag Assistant\n2. Événements déclenchés ? Vérifier en mode debug\n3. Attribution correcte ? Fenêtres appropriées\n4. Doublons ? Une seule source par action',
    '**Données incohérentes Google Ads vs Analytics :**\n\n5-15% d\'écart est normal (modèles d\'attribution différents). Aligner paramètres et utiliser UTM pour traçabilité.'
  ],
  keyPoints: [
    'Fenêtres d\'attribution : 7 jours standard, 30-90 jours pour cycles longs',
    'Google Tag Manager recommandé pour gestion centralisée des tags',
    'CTR benchmarks : Services 2-4%, E-commerce 1.5-3%, B2B 1-2%',
    'ROAS benchmarks : Minimum 2:1, bon 3-4:1, excellent 5:1+',
    'GA4 essentiel : Attribution cross-device et audiences retargeting',
    'Routine hebdo : Lundi analyse, Mercredi mots-clés, Vendredi tests',
    'Tests A/B mensuels structurés sur 4 semaines',
    '5-15% d\'écart Google Ads vs Analytics est normal'
  ]
}
