import { ModuleContent } from '../types'

export const module3: ModuleContent = {
  id: 'module-3',
  title: 'Les Types de Campagnes Google',
  description: 'Maîtrisez les 8 types de campagnes Google Ads et choisissez le bon format selon vos objectifs',
  content: [
    '### Vue d\'ensemble des campagnes Google Ads\n\nGoogle Ads propose huit types de campagnes principaux, chacun adapté à des objectifs marketing spécifiques. Le choix du bon type de campagne est crucial car il détermine où vos annonces seront diffusées, quels formats seront disponibles, et comment Google optimisera vos performances. Une erreur courante est de vouloir tout faire avec un seul type de campagne alors que la combinaison de plusieurs types est souvent la stratégie gagnante.',
    '### Campagnes sur le Réseau de Recherche\n\nLes campagnes Search sont le cœur de Google Ads et souvent le meilleur point de départ pour les annonceurs. Vos annonces textuelles apparaissent quand un utilisateur tape une requête correspondant à vos mots-clés. L\'avantage majeur est l\'intention forte de l\'utilisateur : il cherche activement une solution, ce qui se traduit par des taux de conversion généralement supérieurs aux autres canaux. Le ROI est directement mesurable grâce au lien clair entre la recherche et la conversion.',
    'La structure recommandée est d\'organiser vos campagnes par thématique ou produit, avec des groupes d\'annonces regroupant des mots-clés sémantiquement proches (maximum 15 par groupe). Prévoyez 3-4 annonces par groupe pour tester différents messages. Côté budget, comptez minimum 300€ par mois pour être efficace, avec un CPC moyen de 0,80€ à 3€ selon votre secteur. Les taux de conversion moyens oscillent entre 3% et 8%.',
    '### Campagnes Display\n\nLe Réseau Display de Google couvre plus de 3 millions de sites web et applications, touchant 90% des internautes français. Contrairement au Search qui capte la demande existante, le Display permet de créer de la demande en exposant votre marque à des audiences qui ne vous connaissent pas encore. Les formats incluent des bannières de différentes tailles (728x90, 300x250, 160x600), des annonces responsives qui s\'adaptent automatiquement, et même des formats vidéo.',
    'Le Display excelle dans deux cas d\'usage : la notoriété de marque pour toucher massivement votre cible à moindre coût (CPM de 2-5€), et le retargeting pour recibler les visiteurs de votre site qui n\'ont pas converti. Le CTR moyen est plus faible que le Search (0,4-0,8%) car l\'utilisateur n\'est pas en recherche active, mais les coûts sont également inférieurs (CPC de 0,30-1€). Pour les campagnes de retargeting, le ROAS peut être excellent car vous touchez des audiences déjà engagées.',
    '### Google Shopping : incontournable pour l\'e-commerce\n\nGoogle Shopping affiche vos produits avec photo, prix et avis directement dans les résultats de recherche. Pour les e-commerçants, ce format génère souvent 60-80% du trafic Search car les annonces visuelles captent davantage l\'attention. Le prérequis technique est la création d\'un compte Google Merchant Center et d\'un flux produit contenant pour chaque article : ID unique, titre optimisé, description, prix, disponibilité, image haute résolution, et catégorie Google.',
    '**Optimisation des titres produits Shopping :**\n\n- Placez les mots-clés principaux en début de titre\n- Incluez la marque si elle est connue\n- Ajoutez les attributs clés : couleur, taille, modèle\n- Exemple optimisé : "Robe Noire Zara Femme Midi Taille M"',
    'Le CTR moyen en Shopping est de 1-2%, supérieur aux annonces texte, avec un CPC de 0,40-1,20€. Le taux de conversion oscille entre 2-4% car les utilisateurs qui cliquent ont déjà vu le produit et son prix, ils sont donc pré-qualifiés.',
    '### Campagnes YouTube Ads\n\nYouTube est le deuxième moteur de recherche mondial et touche 47 millions de Français chaque mois. Les campagnes vidéo permettent de raconter votre histoire de manière immersive et émotionnelle. Le format phare TrueView In-Stream diffuse votre vidéo avant, pendant ou après les contenus YouTube, avec un bouton "Ignorer" après 5 secondes. Vous ne payez que si l\'utilisateur regarde plus de 30 secondes ou interagit avec l\'annonce.',
    'Les Bumper Ads de 6 secondes non-skippables sont parfaits pour la notoriété et le rappel de marque. Les YouTube Shorts Ads exploitent le format vertical en pleine croissance (+300% en 2024). Le budget minimum recommandé est de 10€ par jour pour collecter suffisamment de données. YouTube sera traité en détail dans le module 7.',
    '### Campagnes Performance Max : l\'automatisation ultime\n\nLancées en 2023 et constamment améliorées, les campagnes Performance Max représentent la nouvelle direction de Google Ads. Une seule campagne accède simultanément à tous les réseaux Google : Search, Display, YouTube, Shopping, Gmail et Maps. L\'intelligence artificielle de Google décide automatiquement où, quand et comment diffuser vos annonces pour maximiser vos conversions.',
    'Pour fonctionner, vous devez fournir des "assets" variés : images de différentes tailles, vidéos, titres, descriptions, et logos. Google combinera ces éléments de manière dynamique pour créer les annonces les plus performantes. Les résultats sont souvent impressionnants avec une portée maximale et une optimisation continue, mais le contrôle est réduit : vous ne pouvez pas voir précisément où vos annonces apparaissent ni exclure certains réseaux. Prévoyez un budget minimum de 1000€ par mois et 4-6 semaines de patience pour sortir de la phase d\'apprentissage.',
    '### Campagnes Smart : simplicité pour les débutants\n\nLes campagnes Smart (intelligentes) sont conçues pour les petites entreprises sans expertise publicitaire. La configuration prend moins de 10 minutes : vous définissez votre objectif, votre budget, et Google gère tout automatiquement. L\'algorithme choisit les mots-clés, crée les annonces, et optimise les enchères. C\'est un excellent point d\'entrée pour tester Google Ads avec un budget limité (moins de 500€/mois). Cependant, les campagnes Smart ont des limitations importantes : contrôle minimal, données agrégées sans détail granulaire, et performances qui plafonnent rapidement.',
    '### Campagnes d\'Applications Mobiles\n\nSi vous avez une application mobile, les campagnes App vous permettent de promouvoir les téléchargements sur Google Play, YouTube, le Réseau de Recherche et le Display. L\'automatisation est poussée : Google génère automatiquement les créations publicitaires à partir des assets de votre fiche Play Store et optimise vers l\'installation ou les actions in-app. Le coût par installation varie de 0,50€ à 3€ selon la catégorie d\'app, avec les meilleurs résultats pour le gaming, l\'e-commerce et la fintech.'
  ],
  keyPoints: [
    'Search : intention forte, taux de conversion 3-8%, idéal pour démarrer',
    'Display : notoriété + retargeting, CPM 2-5€, touche 90% des internautes',
    'Shopping : 60-80% du trafic e-commerce, CTR 1-2%, produits pré-qualifiés',
    'Performance Max : tous réseaux en une campagne, IA optimise, budget minimum 1000€/mois',
    'Smart : simplicité pour débutants, contrôle limité, idéal pour tester < 500€/mois'
  ]
}
